- name: "{{ _psql_name }}"
  shell: |
    kubectl -n {{ stolon_namespace }} exec -i {{ _pod_name }} -- \
      psql -v ON_ERROR_STOP=0 \
        --username stolon \
        --dbname postgres \
        --host localhost \
        --echo-errors <<!
        {{ _psql_script }}
    !
  register: psql_ret
  ignore_errors: "{{ _psql_ignore_errors | default(false) }}"
  tags: execute_sql
