- name: "{{ _stolonctl_name }}"
  shell:
    kubectl -n {{ stolon_namespace }} exec {{ _pod_name }} -- \
      stolonctl \
        --cluster-name={{ stolon_cluster_label }} \
        --store-backend=kubernetes \
        --kube-resource-kind=configmap \
        {{ _stolonctl_command }}
  register: stolonctl_ret
  retries: "{{ stolonctl_retries | default(10) }}"
  delay: "{{ stolonctl_delay | default(15) }}"
  until: "{{ _stolonctl_until | default(true) }}"
  ignore_errors: "{{ _stolonctl_ignore_errors | default(false) }}"
  tags: data_clusters
